Resources:
  IamUserSecrets:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: mainspark-iam-user-secret
  IamUserS3:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: mainspark-iam-user-s3
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: mainspark-bucket
  IamAccessKeySecrets:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        !Ref IamUserSecrets
  IamAccessKeyS3:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        !Ref IamUserS3      
  IamSecretCredentialsStored:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub /iam/credentials/secrets/${IamUserSecrets}
      SecretString: !Sub '{"ACCESS_KEY":"${IamAccessKeySecrets}","SECRET_KEY":"${IamAccessKeySecrets.SecretAccessKey}"}'
  IamS3CredentialsStored:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub /iam/credentials/s3/${IamUserS3}
      SecretString: !Sub '{"ACCESS_KEY":"${IamAccessKeyS3}","SECRET_KEY":"${IamAccessKeyS3.SecretAccessKey}"}'
  SecretPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'secretsmanager:GetSecretValue'
            Effect: Allow
            Resource:
              - !Ref IamS3CredentialsStored
      PolicyName: SecretPolicy
      Users:
        - !Ref IamUserSecrets
  BucketPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 's3:PutObject'
              - 's3:PutObjectAcl'
              - 's3:GetObject'
              - 's3:GetObjectAcl'
              - 's3:GetObjectVersion'
              - 's3:GetObjectVersionAcl'
            Effect: Allow
            Resource: 
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3Bucket
                  - '/*'
          - Action:
              - 's3:ListBucket'
            Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref S3Bucket
      PolicyName: BucketPolicy
      Users:
        - !Ref IamUserS3