Resources:
  IamUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: mainspark-iam-user
  IamAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        !Ref IamUser
  IamCredentialsStored:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub /iam/credentials/${IamUser}
      SecretString: !Sub '{"ACCESS_KEY":"${IamAccessKey}","SECRET_KEY":"${IamAccessKey.SecretAccessKey}"}'
  SecretPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'secretsmanager:GetSecretValue'
              - 'secretsmanager:List*'
              - 'secretsmanager:DescribeSecret'
            Effect: Allow
            Resource:
              - !Ref IamCredentialsStored
      PolicyName: SecretPolicy
      Users:
        - !Ref IamUser
